name: chatapp
description: "A new Flutter project."

publish_to: 'none'

environment:
  sdk: '>=3.4.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  google_fonts: ^6.2.1
  flutter_svg: ^2.0.10+1
  fl_chart: ^0.68.0
  provider: ^6.1.2
  hive_flutter: ^1.1.0
  sqflite: ^2.3.3+1
  date_time: ^0.11.0
  path: ^1.9.0
  flutter_slidable: ^3.1.1
  flutter_heatmap_calendar: ^1.0.5
  table_calendar: ^3.1.2
  hive: ^2.2.3
  firebase_core: ^3.2.0
  cloud_firestore: ^5.1.0
  firebase_auth: ^5.1.2
  responsive_framework: ^1.4.0
  flutter_screenutil: ^5.9.3
  device_preview: ^1.2.0
  breakpoint: ^1.2.0
  lottie: ^3.1.2
  glass: ^2.0.0+1
  syncfusion_flutter_calendar: ^26.1.42
  image_picker: ^1.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true

  assets:
    - lib/images/backe.png
    - lib/images/apple.png
    - lib/images/er.png
    - lib/images/google.png
    - lib/images/home.png
    - lib/images/peep.png
